### PR TITLE
Better repo structure

### PR DESCRIPTION
**Pull request by lucasfcosta**
- [x] Use eslint instead of jscs
- [x] Fix syntax according to new eslint rules
- [x] Run tests on babel transpilation instead of our source (Related to #44)
- [x] Update NSP
- [x] Improve `publish` task
- [x] Enforce 100% code coverage

### CODE REVIEW

**Comment by lucasfcosta** [comment]
@vieiralucas I'm doing some big structural changes here.
Could you review them please? I would appreciate your skills on this.

Thank you!

**Comment by vieiralucas** [comment]
Have you looked for pre configurations to eslint? What do you think about using eslint configuration from Google? Or crockford? Instead of building your own?
Other than that LGTM
Good work

**Comment by lucasfcosta** [comment]
@vieiralucas Seems like a very good idea, however I need to take a further look at Crockford's and Google's  ESLint rules to answer this with certainty. I'm not aware of their recommendations yet.
Thanks for your feedback!

**Comment by lucasfcosta** [comment]
Here we go.
I'm going to release a new version after this for tests purposes.

**Pull request merged**
