### PR TITLE
[wip] Epic refact

### PR DESCRIPTION
**Pull request by vieiralucas**
- [x] fetch() -> fetch file
- [x] parse(txt) -> parses and returns rule object
- [ ] check(rules, url, userAgent) -> check if user agent can crawl url using a rule obj
- [ ] canCrawl() -> do everything

### CODE REVIEW

**Comment by vieiralucas** [comment]
I think that the parse function is currently a lot of mess, maybe we could refactor it.

**Comment by lucasfcosta** [comment]
@vieiralucas 

Why is robotto using lower case now?

I also thought we could refactor the parse method, but I think there's no other way we can interpret the file without going line by line since it's a sequential file and every line has a different starting keyword/symbol

**Comment by lucasfcosta** [comment]
You can merge this when you want @vieiralucas
Seems good

**Comment by lucasfcosta** [comment]
Merging as requested on facebook

**Comment by lucasfcosta** [comment]
OH GOD I FAILED SO HARD

**Comment by vieiralucas** [comment]
Tralalalalal

**Pull request merged**
